### ISSUE TITLE
Recording feature is not functioning

### ISSUE THREAD

**Issue by febilogi** [SystemSculpt/obsidian-systemsculpt-ai#49] opened 2024-08-17 15:39 UTC
I am currently using version 0.6.2 on my Windows 11 laptop.

I typically activate the recorder with hotkeys and dictate my text. To stop recording, I click the X button on the recording interface. However, today I encountered an issue where I cannot stop the recording.

I have restarted Obsidian and attempted to stop the recording three times, but there seems to be a bug preventing me from doing so and I can't use it now.

.
.
.
Small additional request: it would be helpful to have clear instructions indicating that the X button is used to stop recording, or to implement a dedicated 'Stop' button.

**Comment by SystemSculpt** [comment] 2024-08-18 10:43
Interesting; the X should act just like the toggle-off works; I will look much deeper into this and see what the issue is, marking this as a bug for now and keeping it open until I solve it.

**Comment by febilogi** [comment] 2024-08-20 20:00
I just want to let you know that I tried all older version of SystemSculpt from 0.6.2 until 0.5.1 so I could use the recording feature. But sadly, it has the same problem like the 0.6.2. Probably it is just my laptop that is probematic. But I'll try again after you update this plugin. Keep up the good work! Cheers.

**Comment by SystemSculpt** [comment] 2024-10-14 11:23
good news - i've fixed the recording stop issue. the x button should now work to stop your recordings. this fix is in v0.7.0, out later today. appreciate your patience on this one!

**Closed by SystemSculpt** 2024-10-14 11:23 UTC
Labels: bug
